name: deployment workflow
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy to metacentrum server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.METACENTRUM_HOST }}
        key: ${{ secrets.METACENTRUM_PRIVKEY }}
        port: 22
        script: bash start.sh